declare module 'react-router-dom';

// In typings.d.ts(is Global)
export declare global {
  interface Window {
    getVersion: () => any;
    ethereum;
    web3;
  }
}

/**
const t = {
  _events: {},
  _eventsCount: 1,
  _maxListeners: 100,
  _log: { levels: { TRACE: 0, DEBUG: 1, INFO: 2, WARN: 3, ERROR: 4, SILENT: 5 } },
  _state: { accounts: ['0x24bb7e5ac7e6eeb558c6e5567e6a38a2cc8ebd88'], isConnected: true, isUnlocked: true, initialized: true, isPermanentlyDisconnected: false },
  selectedAddress: '0x24bb7e5ac7e6eeb558c6e5567e6a38a2cc8ebd88',
  chainId: '0x1',
  _jsonRpcConnection: {
    events: { _events: { notification: [null, null] }, _eventsCount: 1 },
    stream: {
      _readableState: {
        objectMode: true,
        highWaterMark: 16,
        buffer: { head: null, tail: null, length: 0 },
        length: 0,
        pipes: {
          _readableState: {
            objectMode: true,
            highWaterMark: 16,
            buffer: { head: null, tail: null, length: 0 },
            length: 0,
            pipesCount: 1,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null,
          },
          readable: true,
          _events: { end: [null, null, null], close: [null, null, null], finish: [null, null], error: [null, null] },
          _eventsCount: 7,
          _writableState: {
            objectMode: true,
            highWaterMark: 16,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: { next: null, entry: null },
          },
          writable: true,
          allowHalfOpen: true,
          _parent: {
            _readableState: {
              objectMode: true,
              highWaterMark: 16,
              buffer: { head: null, tail: null, length: 0 },
              length: 0,
              pipes: {
                _readableState: {
                  objectMode: true,
                  highWaterMark: 16,
                  buffer: { head: null, tail: null, length: 0 },
                  length: 0,
                  pipesCount: 1,
                  flowing: true,
                  ended: false,
                  endEmitted: false,
                  reading: true,
                  sync: false,
                  needReadable: true,
                  emittedReadable: false,
                  readableListening: false,
                  resumeScheduled: false,
                  destroyed: false,
                  defaultEncoding: 'utf8',
                  awaitDrain: 0,
                  readingMore: false,
                  decoder: null,
                  encoding: null,
                },
                readable: true,
                _events: { end: [null, null, null, null], close: [null, null, null, null, null], finish: [null, null, null], error: [null, null, null] },
                _eventsCount: 7,
                _writableState: {
                  objectMode: true,
                  highWaterMark: 16,
                  finalCalled: false,
                  needDrain: false,
                  ending: false,
                  ended: false,
                  finished: false,
                  destroyed: false,
                  decodeStrings: true,
                  defaultEncoding: 'utf8',
                  length: 0,
                  writing: false,
                  corked: 0,
                  sync: false,
                  bufferProcessing: false,
                  writecb: null,
                  writelen: 0,
                  bufferedRequest: null,
                  lastBufferedRequest: null,
                  pendingcb: 0,
                  prefinished: false,
                  errorEmitted: false,
                  bufferedRequestCount: 0,
                  corkedRequestsFree: { next: null, entry: null },
                },
                writable: true,
                allowHalfOpen: true,
                _init: true,
                _haveSyn: true,
                _name: 'metamask-inpage',
                _target: 'metamask-contentscript',
                _targetOrigin: 'http://localhost:3000',
                _targetWindow: {
                  0: {
                    document: {
                      location: {
                        ancestorOrigins: { 0: 'http://localhost:3000' },
                        href: 'about:blank',
                        origin: 'null',
                        protocol: 'about:',
                        host: '',
                        hostname: '',
                        port: '',
                        pathname: 'blank',
                        search: '',
                        hash: '',
                      },
                    },
                    name: '',
                    customElements: {},
                    history: {},
                    locationbar: {},
                    menubar: {},
                    personalbar: {},
                    scrollbars: {},
                    statusbar: {},
                    toolbar: {},
                    status: '',
                    closed: false,
                    length: 0,
                    opener: null,
                    frameElement: {},
                    navigator: {},
                    origin: 'http://localhost:3000',
                    external: {},
                    screen: {},
                    innerWidth: 711,
                    innerHeight: 789,
                    scrollX: 0,
                    pageXOffset: 0,
                    scrollY: 0,
                    pageYOffset: 0,
                    visualViewport: {},
                    screenX: 0,
                    screenY: 0,
                    outerWidth: 1440,
                    outerHeight: 900,
                    devicePixelRatio: 2,
                    screenLeft: 0,
                    screenTop: 0,
                    defaultStatus: '',
                    defaultstatus: '',
                    styleMedia: {},
                    onsearch: null,
                    isSecureContext: true,
                    performance: {
                      timeOrigin: 1646685922676.6,
                      timing: {
                        connectStart: 0,
                        navigationStart: 1646685922677,
                        loadEventEnd: 1646685922687,
                        domLoading: 1646685922677,
                        secureConnectionStart: 0,
                        fetchStart: 0,
                        domContentLoadedEventStart: 1646685922687,
                        responseStart: 0,
                        responseEnd: 1646685922680,
                        domInteractive: 1646685922687,
                        domainLookupEnd: 0,
                        redirectStart: 0,
                        requestStart: 0,
                        unloadEventEnd: 0,
                        unloadEventStart: 0,
                        domComplete: 1646685922687,
                        domainLookupStart: 0,
                        loadEventStart: 1646685922687,
                        domContentLoadedEventEnd: 1646685922687,
                        redirectEnd: 0,
                        connectEnd: 0,
                      },
                      navigation: { type: 0, redirectCount: 0 },
                    },
                    onappinstalled: null,
                    onbeforeinstallprompt: null,
                    crypto: {},
                    indexedDB: {},
                    webkitStorageInfo: {},
                    sessionStorage: {},
                    localStorage: {
                      refreshToken:
                        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJuSndWWG44aHBwR3E0aDJsZ1Y3MmllYXR1Z3VjcnhTR2hjdkY2TmlFS01EYlRiMUJ5enROWnZsNnBv',
                      accessToken:
                        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjA5ODFhMDEwMmYwYzc5OGIzZWE2ZWUiLCxx',
                    },
                    onbeforexrselect: null,
                    onabort: null,
                    onblur: null,
                    oncancel: null,
                    oncanplay: null,
                    oncanplaythrough: null,
                    onchange: null,
                    onclick: null,
                    onclose: null,
                    oncontextmenu: null,
                    oncuechange: null,
                    ondblclick: null,
                    ondrag: null,
                    ondragend: null,
                    ondragenter: null,
                    ondragleave: null,
                    ondragover: null,
                    ondragstart: null,
                    ondrop: null,
                    ondurationchange: null,
                    onemptied: null,
                    onended: null,
                    onerror: null,
                    onfocus: null,
                    onformdata: null,
                    oninput: null,
                    oninvalid: null,
                    onkeydown: null,
                    onkeypress: null,
                    onkeyup: null,
                    onload: null,
                    onloadeddata: null,
                    onloadedmetadata: null,
                    onloadstart: null,
                    onmousedown: null,
                    onmouseenter: null,
                    onmouseleave: null,
                    onmousemove: null,
                    onmouseout: null,
                    onmouseover: null,
                    onmouseup: null,
                    onmousewheel: null,
                    onpause: null,
                    onplay: null,
                    onplaying: null,
                    onprogress: null,
                    onratechange: null,
                    onreset: null,
                    onresize: null,
                    onscroll: null,
                    onsecuritypolicyviolation: null,
                    onseeked: null,
                    onseeking: null,
                    onselect: null,
                    onslotchange: null,
                    onstalled: null,
                    onsubmit: null,
                    onsuspend: null,
                    ontimeupdate: null,
                    ontoggle: null,
                    onvolumechange: null,
                    onwaiting: null,
                    onwebkitanimationend: null,
                    onwebkitanimationiteration: null,
                    onwebkitanimationstart: null,
                    onwebkittransitionend: null,
                    onwheel: null,
                    onauxclick: null,
                    ongotpointercapture: null,
                    onlostpointercapture: null,
                    onpointerdown: null,
                    onpointermove: null,
                    onpointerup: null,
                    onpointercancel: null,
                    onpointerover: null,
                    onpointerout: null,
                    onpointerenter: null,
                    onpointerleave: null,
                    onselectstart: null,
                    onselectionchange: null,
                    onanimationend: null,
                    onanimationiteration: null,
                    onanimationstart: null,
                    ontransitionrun: null,
                    ontransitionstart: null,
                    ontransitionend: null,
                    ontransitioncancel: null,
                    onafterprint: null,
                    onbeforeprint: null,
                    onbeforeunload: null,
                    onhashchange: null,
                    onlanguagechange: null,
                    onmessage: null,
                    onmessageerror: null,
                    onoffline: null,
                    ononline: null,
                    onpagehide: null,
                    onpageshow: null,
                    onpopstate: null,
                    onrejectionhandled: null,
                    onstorage: null,
                    onunhandledrejection: null,
                    onunload: null,
                    chrome: {
                      app: {
                        isInstalled: false,
                        InstallState: { DISABLED: 'disabled', INSTALLED: 'installed', NOT_INSTALLED: 'not_installed' },
                        RunningState: { CANNOT_RUN: 'cannot_run', READY_TO_RUN: 'ready_to_run', RUNNING: 'running' },
                      },
                    },
                    caches: {},
                    cookieStore: {},
                    ondevicemotion: null,
                    ondeviceorientation: null,
                    ondeviceorientationabsolute: null,
                    originAgentCluster: false,
                    trustedTypes: {},
                    speechSynthesis: {},
                    onpointerrawupdate: null,
                    crossOriginIsolated: false,
                    scheduler: {},
                  },
                  document: {
                    location: {
                      ancestorOrigins: {},
                      href: 'http://localhost:3000/game/dashboard',
                      origin: 'http://localhost:3000',
                      protocol: 'http:',
                      host: 'localhost:3000',
                      hostname: 'localhost',
                      port: '3000',
                      pathname: '/game/dashboard',
                      search: '',
                      hash: '',
                    },
                    __reactEvents$t66impehsug: {},
                  },
                  name: '',
                  customElements: {},
                  history: {},
                  locationbar: {},
                  menubar: {},
                  personalbar: {},
                  scrollbars: {},
                  statusbar: {},
                  toolbar: {},
                  status: '',
                  closed: false,
                  length: 1,
                  opener: null,
                  frameElement: null,
                  navigator: {},
                  origin: 'http://localhost:3000',
                  external: {},
                  screen: {},
                  innerWidth: 711,
                  innerHeight: 789,
                  scrollX: 0,
                  pageXOffset: 0,
                  scrollY: 0,
                  pageYOffset: 0,
                  visualViewport: {},
                  screenX: 0,
                  screenY: 0,
                  outerWidth: 1440,
                  outerHeight: 900,
                  devicePixelRatio: 2,
                  screenLeft: 0,
                  screenTop: 0,
                  defaultStatus: '',
                  defaultstatus: '',
                  styleMedia: {},
                  onsearch: null,
                  isSecureContext: true,
                  performance: {
                    timeOrigin: 1646685660765.6,
                    timing: {
                      connectStart: 1646685660766,
                      navigationStart: 1646685660765,
                      loadEventEnd: 1646685661338,
                      domLoading: 1646685660795,
                      secureConnectionStart: 0,
                      fetchStart: 1646685660766,
                      domContentLoadedEventStart: 1646685661032,
                      responseStart: 1646685660781,
                      responseEnd: 1646685660790,
                      domInteractive: 1646685660847,
                      domainLookupEnd: 1646685660766,
                      redirectStart: 0,
                      requestStart: 1646685660779,
                      unloadEventEnd: 1646685660792,
                      unloadEventStart: 1646685660792,
                      domComplete: 1646685661338,
                      domainLookupStart: 1646685660766,
                      loadEventStart: 1646685661338,
                      domContentLoadedEventEnd: 1646685661032,
                      redirectEnd: 0,
                      connectEnd: 1646685660766,
                    },
                    navigation: { type: 1, redirectCount: 0 },
                  },
                  onappinstalled: null,
                  onbeforeinstallprompt: null,
                  crypto: {},
                  indexedDB: {},
                  webkitStorageInfo: {},
                  sessionStorage: {},
                  localStorage: {
                    refreshToken:
                      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJuSndWWG44aHBwR3E0aDJsZ1Y3Mml',
                    accessToken:
                      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjA5ODFhMDEwMmYwYzc5OGIzZWE',
                  },
                  onbeforexrselect: null,
                  onabort: null,
                  onblur: null,
                  oncancel: null,
                  oncanplay: null,
                  oncanplaythrough: null,
                  onchange: null,
                  onclick: null,
                  onclose: null,
                  oncontextmenu: null,
                  oncuechange: null,
                  ondblclick: null,
                  ondrag: null,
                  ondragend: null,
                  ondragenter: null,
                  ondragleave: null,
                  ondragover: null,
                  ondragstart: null,
                  ondrop: null,
                  ondurationchange: null,
                  onemptied: null,
                  onended: null,
                  onerror: null,
                  onfocus: null,
                  onformdata: null,
                  oninput: null,
                  oninvalid: null,
                  onkeydown: null,
                  onkeypress: null,
                  onkeyup: null,
                  onload: null,
                  onloadeddata: null,
                  onloadedmetadata: null,
                  onloadstart: null,
                  onmousedown: null,
                  onmouseenter: null,
                  onmouseleave: null,
                  onmousemove: null,
                  onmouseout: null,
                  onmouseover: null,
                  onmouseup: null,
                  onmousewheel: null,
                  onpause: null,
                  onplay: null,
                  onplaying: null,
                  onprogress: null,
                  onratechange: null,
                  onreset: null,
                  onresize: null,
                  onscroll: null,
                  onsecuritypolicyviolation: null,
                  onseeked: null,
                  onseeking: null,
                  onselect: null,
                  onslotchange: null,
                  onstalled: null,
                  onsubmit: null,
                  onsuspend: null,
                  ontimeupdate: null,
                  ontoggle: null,
                  onvolumechange: null,
                  onwaiting: null,
                  onwebkitanimationend: null,
                  onwebkitanimationiteration: null,
                  onwebkitanimationstart: null,
                  onwebkittransitionend: null,
                  onwheel: null,
                  onauxclick: null,
                  ongotpointercapture: null,
                  onlostpointercapture: null,
                  onpointerdown: null,
                  onpointermove: null,
                  onpointerup: null,
                  onpointercancel: null,
                  onpointerover: null,
                  onpointerout: null,
                  onpointerenter: null,
                  onpointerleave: null,
                  onselectstart: null,
                  onselectionchange: null,
                  onanimationend: null,
                  onanimationiteration: null,
                  onanimationstart: null,
                  ontransitionrun: null,
                  ontransitionstart: null,
                  ontransitionend: null,
                  ontransitioncancel: null,
                  onafterprint: null,
                  onbeforeprint: null,
                  onbeforeunload: null,
                  onhashchange: null,
                  onlanguagechange: null,
                  onmessage: null,
                  onmessageerror: null,
                  onoffline: null,
                  ononline: null,
                  onpagehide: null,
                  onpageshow: null,
                  onpopstate: null,
                  onrejectionhandled: null,
                  onstorage: null,
                  onunhandledrejection: null,
                  onunload: null,
                  chrome: {
                    app: {
                      isInstalled: false,
                      InstallState: { DISABLED: 'disabled', INSTALLED: 'installed', NOT_INSTALLED: 'not_installed' },
                      RunningState: { CANNOT_RUN: 'cannot_run', READY_TO_RUN: 'ready_to_run', RUNNING: 'running' },
                    },
                  },
                  caches: {},
                  cookieStore: {},
                  ondevicemotion: null,
                  ondeviceorientation: null,
                  ondeviceorientationabsolute: null,
                  originAgentCluster: false,
                  trustedTypes: {},
                  speechSynthesis: {},
                  onpointerrawupdate: null,
                  crossOriginIsolated: false,
                  scheduler: {},
                  webpackChunkreact_demo: [[['src_components_translate_languages_en_json'], {}]],
                  __REACT_DEVTOOLS_GLOBAL_HOOK__: { renderers: {}, supportsFiber: true },
                  __reactRefreshInjected: true,
                  __EMOTION_REACT_11__: true,
                },
              },
              pipesCount: 1,
              flowing: true,
              ended: false,
              endEmitted: false,
              reading: true,
              sync: false,
              needReadable: true,
              emittedReadable: false,
              readableListening: false,
              resumeScheduled: false,
              destroyed: false,
              defaultEncoding: 'utf8',
              awaitDrain: 0,
              readingMore: false,
              decoder: null,
              encoding: null,
            },
            readable: true,
            _events: { end: [null, null, null, null, null], close: [null, null, null, null, null], finish: [null, null, null, null], error: [null, null, null, null] },
            _eventsCount: 7,
            _writableState: {
              objectMode: true,
              highWaterMark: 16,
              finalCalled: false,
              needDrain: false,
              ending: false,
              ended: false,
              finished: false,
              destroyed: false,
              decodeStrings: true,
              defaultEncoding: 'utf8',
              length: 0,
              writing: false,
              corked: 0,
              sync: false,
              bufferProcessing: false,
              writecb: null,
              writelen: 0,
              bufferedRequest: null,
              lastBufferedRequest: null,
              pendingcb: 0,
              prefinished: false,
              errorEmitted: false,
              bufferedRequestCount: 0,
              corkedRequestsFree: { next: null, entry: null },
            },
            writable: true,
            allowHalfOpen: true,
            _substreams: {},
          },
          _name: 'metamask-provider',
        },
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
      },
      readable: true,
      _events: { end: [null, null, null, null], close: [null, null, null, null, null], finish: [null, null, null], error: [null, null, null] },
      _eventsCount: 7,
      _writableState: {
        objectMode: true,
        highWaterMark: 16,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: { next: null, entry: null },
      },
      writable: true,
      allowHalfOpen: true,
    },
  },
  _rpcEngine: { _events: {}, _eventsCount: 0, _middleware: [null, null, null] },
  _sentWarnings: { enable: false, experimentalMethods: false, send: false, events: { close: false, data: false, networkChanged: false, notification: false } },
  networkVersion: '1',
  isMetaMask: true,
  _metamask: {},
};
*/
